config/routes.rb
Rails.application.routes.draw do
  root 'points#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create]
  resources :points
  resources :technologies, except: [:show]
  resources :centers, except: [:show]
  resources :zones
  resources :devices
  resources :actives
  resources :modifications
  resources :reforms
  resources :activities
  resources :tasks
  resources :unities
  resources :uses
  resources :ips

end

app/models/active.rb
class Active < ApplicationRecord
  belongs_to :device
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :task
  belongs_to :reform
end

app/models/center.rb
# == Schema Information
#
# Table name: centers
#
#  id         :bigint(8)        not null, primary key
#  nombre     :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  zone_id    :bigint(8)
#

class Center < ApplicationRecord
  has_many :point, dependent: :destroy
  belongs_to :zone
  validates :nombre, :zone_id, presence: true

  def to_s
    nombre
  end
end

app/models/device.rb
# == Schema Information
#
# Table name: devices
#
#  id         :bigint(8)        not null, primary key
#  nombre     :string(255)
#  tipo       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Device < ApplicationRecord
  has_many :actives, dependent: :destroy
  has_many :ips
  validates :nombre, presence: true
end

app/models/ip.rb
class Ip < ApplicationRecord
  belongs_to :use
  belongs_to :device
  belongs_to :point
  # La siguiente sentencia por medio de expresiones regulares valida q el numero ingresado sea una IP valida
  validates :ip, format: { with: /(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)/, message: "Ingrese una direccion IP Valida" }
end

app/models/modification.rb
class Modification < ApplicationRecord
  has_many :reform
end

app/models/point.rb
# == Schema Information
#
# Table name: points
#
#  id            :bigint(8)        not null, primary key
#  codigo        :integer
#  nombre        :string(255)
#  direccion     :string(255)
#  telefono      :string(255)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  picture       :string(255)
#  technology_id :bigint(8)
#  center_id     :bigint(8)
#  serial        :string(255)
#  celda         :string(255)
#

class Point < ApplicationRecord
  mount_uploader :picture, FotoUploader
  has_many :reforms
  has_many :ips
  belongs_to :technology
  belongs_to :center
  # Se implementan las validaciones.
  validates :codigo, :nombre, :direccion, :telefono, :center_id, presence: true

end

app/models/reform.rb
class Reform < ApplicationRecord
  belongs_to :point
  belongs_to :modification
  has_many :activity
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :activity
end

app/models/technology.rb
# == Schema Information
#
# Table name: technologies
#
#  id          :bigint(8)        not null, primary key
#  descripcion :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Technology < ApplicationRecord
  # Con has many creo la relacion con la tabla puntos
  # con destroy implemento la eliminacion en cascada
  has_many :point, dependent: :destroy
  validates :descripcion, presence: true
end

app/models/unity.rb
class Unity < ApplicationRecord
end

app/models/use.rb
class Use < ApplicationRecord
  has_many :ips
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string(255)
#  nombre          :string(255)
#  cedula          :integer
#  password_digest :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  # Cifrado de la contraseña del usuario
  has_secure_password validations: false

  validates :email, uniqueness: true, format: /@record.com.co/
  validates :password, presence: true, on: :create
  validates :password, length: { in: 6..20 }, allow_nil: true
  validates :nombre, presence: true
  validates :cedula, presence: true
end

app/models/zone.rb
# == Schema Information
#
# Table name: zones
#
#  id         :bigint(8)        not null, primary key
#  nombre     :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Zone < ApplicationRecord
  has_many :centers, dependent: :destroy
  validates :nombre, presence: true

  accepts_nested_attributes_for :centers

  def to_s
    nombre
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @task = Task.all
  end

  def new
    @task = Task.new
    @task.activity_id = params[:activity_id]
    @visibilidad = params[:visible]
  end

  def create
    @task = Task.new(task_params)
    session[:return_to] ||= request.referer
    if @task.save
      redirect_to session.delete(:return_to), notice: "Se agrego una nueva tarea"
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      session[:return_to] ||= request.referer
      redirect_to session.delete(:return_to), notice: "Esta Tarea ha sido actualizada"
    else
      render :edit
    end
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    session[:return_to] ||= request.referer
    redirect_to session.delete(:return_to), alert: "La tarea fue eliminida"
  end

  private
    def task_params
      params.require(:task).permit(:descripcion, :cantidad, :valor_unitario, :unity_id, :activity_id)
    end
end

app/helpers/actives_helper.rb
module ActivesHelper
end

app/helpers/centers_helper.rb
module CentersHelper
end

app/helpers/ips_helper.rb
module IpsHelper
end

app/helpers/points_helper.rb
module PointsHelper
  def form_title
    @p.new_record? ? "Registrar Nuevo Punto de Venta" : "Modificar Punto de Venta"
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/uses_helper.rb
module UsesHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/tasks/_form.html.erb
<div id="task-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= title %></h4>
      </div>
      <%= form_for @task, remote: true do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <%= f.text_area :descripcion, maxlength:200, class: "form-control input-lg", placeholder: "Ingresar Nueva Tarea" %>
          </div>
          <% if @visibilidad == "true" %>
            <div class="form-group" data-toggle='tooltip' title='Actividad Predefinida, Elemento desactivado'>
              <% ac = Activity.find(@task.activity_id) %>
              <label class="control-label col-sm-6">Actividad: <%=ac.descripcion%> </label>
              <%= f.text_field :activity_id, class: "form-control input-lg", value: (ac.id).to_i, readonly: @visibilidad %>
            </div>
          <% elsif @visibilidad == "false"  %>
            <div class="form-group">
              <label class="control-label col-sm-6">Seleccione la Actividad a la que Corresponde: </label>
              <%= f.select :activity_id, options_for_select(Activity.all.collect { |a| [a.descripcion, a.id]},@task.activity_id), {:include_blank => true}, class: "form-control input-lg"%>
            </div>
          <% else %>
            <div class="form-group">
              <label class="control-label col-sm-6">Actividad: </label>
              <% ac = Activity.find(@task.activity_id) %>
              <label class="control-label col-sm-6"><%=ac.descripcion%> </label>
              <%= f.text_field :activity_id, class: "form-control input-lg", value: ac.id, readonly: "true" %>
            </div>
          <% end %>
          <div class="form-group">
            <%= f.number_field :cantidad, in: 0..10000000, step: 0.01, class: "form-control input-lg", placeholder: "Ingresar Cantidad" %>
          </div>
          <div class="form-group">
            <label class="control-label col-sm-6">Seleccione la Unidad de Medida: </label>
            <%= f.select :unity_id, options_for_select(Unity.all.collect { |u| [u.unidad+" ("+u.sigla+")", u.id]},@task.unity_id), {:include_blank => true}, class: "form-control input-lg"%>
          </div>
          <div class="form-group">
            <div class="input-group">
                <div class="input-group-addon">$</div>
                <%= f.number_field :valor_unitario, in: 0..10000000, step:'any', class: "form-control input-lg", placeholder: "Ingresar Valor Unitario" %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <%= f.submit "Registrar", class: "btn btn-danger btn-lg btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/_row.html.erb
<tr id="<%= task.id %>">
  <td><%= task.descripcion %></td>
  <td><%= task.activity_id %></td>
  <td><%= task.cantidad %></td>
  <td><%= task.unity_id %></td>
  <td><%= task.valor_unitario %></td>
  <td>
    <%= link_to "Editar", edit_task_path(task), remote: true %>
  </td>
</tr>

app/views/tasks/create.js.erb
<% if @task.errors.empty? %>
  // add the row to the table, show alert and hide modal
  $('table tbody').append(' <%= j render "row", task: @task %>');
  $('.alert-success').html("La tarea ha sido creada").show();
  $('#task-modal').modal('hide');
<% else %>
  // show first error
  alert('ERROR: El campo no puede estar vacio');
<% end %>

app/views/tasks/edit.js.erb
$('<%= j render "form", title: "Editar Tareas" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/tasks/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
      <div class="page-header icons">
        <h1>Listado Tareas</h1>
        <%= link_to "<span class='glyphicon glyphicon-arrow-left' data-toggle='tooltip' title='ir a Inicio'></span>".html_safe, points_path %>
        <!-- Se desabilitan estos iconos porque solo deben ser registradas las actividades o las tareas a travez de la hoja de vida del punto de venta -->
        <!-- <#%= link_to "<span class='glyphicon glyphicon-plus' data-toggle='tooltip' title='Registrar Nueva Tarea'></span>".html_safe, new_task_path, remote: true %> -->
        <!-- <#%=  link_to "<span class='glyphicon glyphicon-list-alt' data-toggle='tooltip' title='Registrar Nueva Actividad'></span>".html_safe, new_activity_path, remote: true %> -->
        <%= link_to "<span class='glyphicon glyphicon-scale' data-toggle='tooltip' title='Registrar Nueva Unidad de Medida'></span>".html_safe, new_unity_path, remote: true %>
      </div>
      <div class="fondo_tasks">
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>DESCRIPCION</th>
                <th>ACTIVIDAD</th>
                <th>CANTIDAD</th>
                <th>UNIDAD</th>
                <th colspan="2" text-align="right">V. UNITARIO</th>
                <th colspan="2" text-align="right">V. TOTAL</th>
                <th>ACCION</th>
              </tr>
            </thead>
            <% @task.each do |task| %>
            <tr>
              <td><%= task.descripcion %></td>
              <td><%= (Activity.find(task.activity_id)).descripcion %></td>
              <td align="center"><%= number_with_delimiter(task.cantidad, separator:',') %></td>
              <td align="center"><% u=Unity.find(task.unity_id) %><%=u.sigla%></td>
              <td align="right">$</td>
              <td align="right"><%= number_with_delimiter(task.valor_unitario, delimiter:'.', separator:',') %></td>
              <td align="right">$</td>
              <td align="right"><% total= (task.cantidad)*(task.valor_unitario) %><%=number_with_delimiter(total, delimiter:'.', separator:',')%></td>
              <td align="center">
                <div class="icons">
                  <%= link_to "<span class='glyphicon glyphicon-pencil' data-toggle='tooltip' title='Modificar Tarea'></span>".html_safe, edit_task_path(task), remote: true %>
                  <%= link_to "<span class='glyphicon glyphicon-trash' data-toggle='tooltip' title='Elimina esta Tarea'></span>".html_safe, task, method: :delete, data: { confirm: "¿Estás seguro de eliminar esta Tareas?" } %>
                </div>
              </td>
            </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/new.js.erb
$('<%= j render "form", title: "Registrar Nueva Tarea" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/tasks/update.js.erb
<% if @task.errors.empty? %>
  // add the row to the table, show alert and hide modal
  $('table tbody tr#<%= @task.id %>').replaceWith(' <%= j render "row", task: @task %>');
  $('.alert-success').html("La tarea ha sido modificada").show();
  $('#task-modal').modal('hide');
<% else %>
  // show first error
  alert('<%= @task.errors.full_messages[0] %>');
<% end %>