config/routes.rb
Rails.application.routes.draw do
  root 'points#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create]
  resources :points
  resources :technologies, except: [:show]
  resources :centers, except: [:show]
  resources :zones
  resources :devices
  resources :actives
  resources :modifications
  resources :reforms
  resources :activities
  resources :tasks
  resources :unities
  resources :uses
  resources :ips

end

app/models/active.rb
class Active < ApplicationRecord
  belongs_to :device
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :task
  belongs_to :reform
end

app/models/center.rb
# == Schema Information
#
# Table name: centers
#
#  id         :bigint(8)        not null, primary key
#  nombre     :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  zone_id    :bigint(8)
#

class Center < ApplicationRecord
  has_many :point, dependent: :destroy
  belongs_to :zone
  validates :nombre, :zone_id, presence: true

  def to_s
    nombre
  end
end

app/models/device.rb
# == Schema Information
#
# Table name: devices
#
#  id         :bigint(8)        not null, primary key
#  nombre     :string(255)
#  tipo       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Device < ApplicationRecord
  has_many :actives, dependent: :destroy
  has_many :ips
  validates :nombre, presence: true
end

app/models/ip.rb
class Ip < ApplicationRecord
  belongs_to :use
  belongs_to :device
  belongs_to :point
  # La siguiente sentencia por medio de expresiones regulares valida q el numero ingresado sea una IP valida
  validates :ip, format: { with: /(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)/, message: "Ingrese una direccion IP Valida" }
end

app/models/modification.rb
class Modification < ApplicationRecord
  has_many :reform
end

app/models/point.rb
# == Schema Information
#
# Table name: points
#
#  id            :bigint(8)        not null, primary key
#  codigo        :integer
#  nombre        :string(255)
#  direccion     :string(255)
#  telefono      :string(255)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  picture       :string(255)
#  technology_id :bigint(8)
#  center_id     :bigint(8)
#  serial        :string(255)
#  celda         :string(255)
#

class Point < ApplicationRecord
  mount_uploader :picture, FotoUploader
  has_many :reforms
  has_many :ips
  belongs_to :technology
  belongs_to :center
  # Se implementan las validaciones.
  validates :codigo, :nombre, :direccion, :telefono, :center_id, presence: true

end

app/models/reform.rb
class Reform < ApplicationRecord
  belongs_to :point
  belongs_to :modification
  has_many :activity
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :activity
end

app/models/technology.rb
# == Schema Information
#
# Table name: technologies
#
#  id          :bigint(8)        not null, primary key
#  descripcion :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Technology < ApplicationRecord
  # Con has many creo la relacion con la tabla puntos
  # con destroy implemento la eliminacion en cascada
  has_many :point, dependent: :destroy
  validates :descripcion, presence: true
end

app/models/unity.rb
class Unity < ApplicationRecord
end

app/models/use.rb
class Use < ApplicationRecord
  has_many :ips
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string(255)
#  nombre          :string(255)
#  cedula          :integer
#  password_digest :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  # Cifrado de la contraseña del usuario
  has_secure_password validations: false

  validates :email, uniqueness: true, format: /@record.com.co/
  validates :password, presence: true, on: :create
  validates :password, length: { in: 6..20 }, allow_nil: true
  validates :nombre, presence: true
  validates :cedula, presence: true
end

app/models/zone.rb
# == Schema Information
#
# Table name: zones
#
#  id         :bigint(8)        not null, primary key
#  nombre     :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Zone < ApplicationRecord
  has_many :centers, dependent: :destroy
  validates :nombre, presence: true

  accepts_nested_attributes_for :centers

  def to_s
    nombre
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController

  def index
    @d = Device.all
  end

  def new
    @d = Device.new
  end

  def create
    @d = Device.new(device_params)
    if @d.save
      redirect_to devices_path, notice: "Se agregó un nuevo dispositivo"
    end
  end

  def show
    @d = Device.find(params[:id])
  end

  def edit
    @d = Device.find(params[:id])
  end

  def update
    @d = Device.find(params[:id])
    if @d.update(device_params)
      redirect_to devices_path, notice: "Este dispositivo ha sido actualizado"
    else
      render :edit
    end
  end

  def destroy
    device = Device.find(params[:id])
    device.destroy
    redirect_to devices_path, alert: "El dispositivo fue eliminado"
  end

  private
    def device_params
      params.require(:device).permit(:nombre, :tipo)
    end


end

app/helpers/actives_helper.rb
module ActivesHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/ips_helper.rb
module IpsHelper
end

app/helpers/points_helper.rb
module PointsHelper
  def form_title
    @p.new_record? ? "Registrar Nuevo Punto de Venta" : "Modificar Punto de Venta"
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/uses_helper.rb
module UsesHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/devices/_form.html.erb
<div id="device-modal" class="modal fade"> <!-- product-modal -->
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= title %></h4>
      </div>
      <%= form_for @d, remote: true do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <%= f.text_field :nombre, class: "form-control input-lg", placeholder: "Descripcion Nuevo Dispositivo (Ej: Mouse, Teclado, etc)" %>
          </div>
          <div class="form-group">
            <%= f.text_field :tipo, class: "form-control input-lg", placeholder: "Tipo de Dispositivo (Ej: Si es un teclado, Tipo = USB o PS2)" %>
          </div>
        </div>
        <div class="modal-footer">
          <%= f.submit "Registrar", class: "btn btn-danger btn-lg btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/devices/_row.html.erb
<tr id="<%= device.id %>">
  <td><%= device.nombre %></td>
  <td><%= device.tipo %></td>
  <td>
    <%= link_to "Modificar", edit_device_path(device), remote: true %>
  </td>
</tr>

app/views/devices/create.js.erb
<% if @d.errors.empty? %>
  // add the row to the table, show alert and hide modal
  $('table tbody').append(' <%= j render "row", device: @d %>');
  $('.alert-success').html("El dispositivo ha sido creado").show();
  $('#center-modal').modal('hide');
<% else %>
  // show first error
  alert('ERROR: Especifique que dispositivo desea registrar');
<% end %>

app/views/devices/edit.js.erb
$('<%= j render "form", title: "Modificar Dispositivo" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/devices/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <div class="page-header icons">
        <h1>Dispositivos</h1>
        <%= link_to "<span class='glyphicon glyphicon-arrow-left' data-toggle='tooltip' title='ir a Inicio'></span>".html_safe, points_path %>
        <%= link_to "<span class='glyphicon glyphicon-tag' data-toggle='tooltip' title='ir a Activo Fijo'></span>".html_safe, actives_path %>
        <%= link_to "<span class='glyphicon glyphicon-plus' data-toggle='tooltip' title='Registrar Nuevo Dispositivo'></span>".html_safe, new_device_path, remote: true %>
      </div>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>NOMBRE</th>
              <th>TIPO</th>
              <th>ACCION</th>
            </tr>
          </thead>
          <% @d.each do |device| %>
          <tr>
            <td><%= device.nombre %></td>
            <td><%= device.tipo %></td>
            <td><div class="icons"><%= link_to "<span class='glyphicon glyphicon-pencil' data-toggle='tooltip' title='Modificar Dispositivo'></span>".html_safe, edit_device_path(device), remote: true %>
              <%= link_to "<span class='glyphicon glyphicon-trash' data-toggle='tooltip' title='Eliminar el dispositivo'></span>".html_safe, device, method: :delete, data: { confirm: "¿Estás seguro de eliminar este dispositivo?" }, class: "destroy-room-btn" %></div></td>
          </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/devices/new.js.erb
$('<%= j render "form", title: "Registrar Nuevo Dispositivo" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/devices/update.js.erb
<% if @d.errors.empty? %>
  // add the row to the table, show alert and hide modal
  $('table tbody tr#<%= @d.id %>').replaceWith(' <%= j render "row", device: @d %>');
  $('.alert-success').html("El dispositivo ha sido modificado").show();
  $('#center-modal').modal('hide');
<% else %>
  // show first error
  alert('<%= @d.errors.full_messages[0] %>');
<% end %>