config/routes.rb
Rails.application.routes.draw do
  root 'points#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create]
  resources :points
  resources :technologies, except: [:show]
  resources :centers, except: [:show]
  resources :zones
  resources :devices
  resources :actives
  resources :modifications
  resources :reforms
  resources :activities
  resources :tasks
  resources :unities
  resources :uses
  resources :ips

end

app/models/active.rb
class Active < ApplicationRecord
  belongs_to :device
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :task
  belongs_to :reform
end

app/models/center.rb
# == Schema Information
#
# Table name: centers
#
#  id         :bigint(8)        not null, primary key
#  nombre     :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  zone_id    :bigint(8)
#

class Center < ApplicationRecord
  has_many :point, dependent: :destroy
  belongs_to :zone
  validates :nombre, :zone_id, presence: true

  def to_s
    nombre
  end
end

app/models/device.rb
# == Schema Information
#
# Table name: devices
#
#  id         :bigint(8)        not null, primary key
#  nombre     :string(255)
#  tipo       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Device < ApplicationRecord
  has_many :actives, dependent: :destroy
  has_many :ips
  validates :nombre, presence: true
end

app/models/ip.rb
class Ip < ApplicationRecord
  belongs_to :use
  belongs_to :device
  belongs_to :point
  # La siguiente sentencia por medio de expresiones regulares valida q el numero ingresado sea una IP valida
  validates :ip, format: { with: /(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)/, message: "Ingrese una direccion IP Valida" }
end

app/models/modification.rb
class Modification < ApplicationRecord
  has_many :reform
end

app/models/point.rb
# == Schema Information
#
# Table name: points
#
#  id            :bigint(8)        not null, primary key
#  codigo        :integer
#  nombre        :string(255)
#  direccion     :string(255)
#  telefono      :string(255)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  picture       :string(255)
#  technology_id :bigint(8)
#  center_id     :bigint(8)
#  serial        :string(255)
#  celda         :string(255)
#

class Point < ApplicationRecord
  mount_uploader :picture, FotoUploader
  has_many :reforms
  has_many :ips
  belongs_to :technology
  belongs_to :center
  # Se implementan las validaciones.
  validates :codigo, :nombre, :direccion, :telefono, :center_id, presence: true

end

app/models/reform.rb
class Reform < ApplicationRecord
  belongs_to :point
  belongs_to :modification
  has_many :activity
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :activity
end

app/models/technology.rb
# == Schema Information
#
# Table name: technologies
#
#  id          :bigint(8)        not null, primary key
#  descripcion :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Technology < ApplicationRecord
  # Con has many creo la relacion con la tabla puntos
  # con destroy implemento la eliminacion en cascada
  has_many :point, dependent: :destroy
  validates :descripcion, presence: true
end

app/models/unity.rb
class Unity < ApplicationRecord
end

app/models/use.rb
class Use < ApplicationRecord
  has_many :ips
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string(255)
#  nombre          :string(255)
#  cedula          :integer
#  password_digest :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  # Cifrado de la contraseña del usuario
  has_secure_password validations: false

  validates :email, uniqueness: true, format: /@record.com.co/
  validates :password, presence: true, on: :create
  validates :password, length: { in: 6..20 }, allow_nil: true
  validates :nombre, presence: true
  validates :cedula, presence: true
end

app/models/zone.rb
# == Schema Information
#
# Table name: zones
#
#  id         :bigint(8)        not null, primary key
#  nombre     :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Zone < ApplicationRecord
  has_many :centers, dependent: :destroy
  validates :nombre, presence: true

  accepts_nested_attributes_for :centers

  def to_s
    nombre
  end
end

app/controllers/centers_controller.rb
class CentersController < ApplicationController

  def index
    @c = Center.all
  end

  def new
    @c = Center.new
    @c.zone_id = params[:zone_id]
    @visibilidad = params[:visible]
  end

  def create
    @c = Center.new(center_params)
    session[:return_to] ||= request.referer
    if @c.save
      redirect_to session.delete(:return_to), notice: "Se agrego el nuevo centro de costos '#{@c.nombre}'"
    end
  end

  def edit
    @c = Center.find(params[:id])
  end

  def update
    @c = Center.find(params[:id])
    #En su acción de edición, guardar la URL solicitante en el hash sesión, que está disponible en varias solicitudes:
    session[:return_to] ||= request.referer
    if @c.update(center_params)
      #edireccionan a él en su acción de actualización, después de una exitosa Guardar:
      redirect_to session.delete(:return_to), notice: "El centro de costos '#{@c.nombre}' ha sido actualizado"
    else
      render :edit
    end
  end

  def destroy
    center = Center.find(params[:id])
    center.destroy
    #En su acción de edición, guardar la URL solicitante en el hash sesión, que está disponible en varias solicitudes:
    session[:return_to] ||= request.referer
    #edireccionan a él en su acción de actualización, después de una exitosa Guardar:
    redirect_to session.delete(:return_to), alert: "El Centro de Costos fue eliminado, y todos los registros de puntos de venta que lo contenian"
  end

private
  def center_params
    params.require(:center).permit(:nombre, :zone_id)
  end
end

app/helpers/actives_helper.rb
module ActivesHelper
end

app/helpers/centers_helper.rb
module CentersHelper
end

app/helpers/ips_helper.rb
module IpsHelper
end

app/helpers/points_helper.rb
module PointsHelper
  def form_title
    @p.new_record? ? "Registrar Nuevo Punto de Venta" : "Modificar Punto de Venta"
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/uses_helper.rb
module UsesHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/centers/_form.html.erb
<div id="center-modal" class="modal fade"> <!-- product-modal -->
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= title %></h4>
      </div>
      <% if @c.errors.any? %>
        <div class="alert alert-danger">
          <ul>
          <% @c.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_for @c, remote: true do |f| %>
        <div class="modal-body">
          <div class="form-group" data-toggle='tooltip' title='Ingrese el nombre del Centro de Costos'>
            <%= f.text_field :nombre, class: "form-control input-lg", placeholder: "Nombre Nuevo Centro de Costos" %>
          </div>
          <% if @visibilidad == "true" %>
            <div class="form-group" data-toggle='tooltip' title='Zona Predefinida, Elemento deshabilitado'>
              <% z = Zone.find(@c.zone_id) %>
              <label class="control-label col-sm-6">Zona: <%=z.nombre%> </label>
              <%= f.text_field :zone_id, class: "form-control input-lg", value: z.id, readonly: @visibilidad %>
            </div>
          <% elsif @visibilidad == "false"  %>
          <div class="form-group">
            <label class="control-label col-sm-6">Seleccione una Zona: </label>
            <%= f.select :zone_id, options_for_select(Zone.all.collect { |z| [z.nombre, z.id]}), {:include_blank => true}, class: "form-control input-lg"%>
          </div>
          <% else %>
          <div class="form-group">
            <label class="control-label col-sm-6">Seleccione una Zona: </label>
            <%= f.select :zone_id, options_for_select(Zone.all.collect { |z| [z.nombre, z.id]},@c.zone_id), {:include_blank => true}, class: "form-control input-lg"%>
          </div>
          <% end %>
        </div>
        <div class="modal-footer">
          <%= f.submit "Registrar", class: "btn btn-danger btn-lg btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/centers/_row.html.erb
<tr id="<%= center.id %>">
  <td><%= center.nombre %></td>
  <td><%= center.zone_id %>
    <%= link_to "Modificar", edit_center_path(center), remote: true %>
  </td>
</tr>

app/views/centers/create.js.erb
<% if @c.errors.empty? %>
  // add the row to the table, show alert and hide modal
  $('table tbody').append(' <%= j render "row", center: @c %>');
  $('.alert-success').html("El centro de costos ha sido creada").show();
  $('#active-modal').modal('hide');
<% else %>
  // show first error
  alert('ERROR: Debe diligenciar todos los campos del formulario');
<% end %>

app/views/centers/edit.js.erb
$('<%= j render "form", title: "Editar Centro de Costos" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/centers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <div class="page-header">
        <h1>Listado Completo Centros de Costos</h1>
        <div class="icons">
          <%= link_to "<span class='glyphicon glyphicon-arrow-left' data-toggle='tooltip' title='ir a Inicio'></span>".html_safe, points_path %>
          <%= link_to "<span class='glyphicon glyphicon-globe' data-toggle='tooltip' title='ir a Zonas (Para agregar un nuevo centro de costos)'></span>".html_safe, zones_path %>
          <%= link_to "<span class='glyphicon glyphicon-plus' data-toggle='tooltip' title='Registrar Nuevo Centro de Costos para esta Zona'></span>".html_safe, new_center_path(:zone_id=>nil, :visible => false ), remote: true %>
        </div>
      </div>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>NOMBRE</th>
            <th>ZONA</th>
            <th>ACCION</th>
          </tr>
        </thead>
        <% @c.each do |center| %>
        <tr>
          <td><%= center.nombre %></td>
          <td><% z=Zone.find(center.zone_id) %><%=z.nombre %></td>
          <td><div class="icons"><%= link_to "<span class='glyphicon glyphicon-pencil' data-toggle='tooltip' title='Modificar Centro Costo'></span>".html_safe, edit_center_path(center), remote: true %>
            <%= link_to "<span class='glyphicon glyphicon-trash' data-toggle='tooltip' title='Elimina el Centro de Costo y los puntos de venta que lo contienen'></span>".html_safe, center, method: :delete, data: { confirm: "¿Estás seguro de eliminar este centro de costos, y por consiguiente todos los puntos de venta que lo contienen?, de no ser asi cambie primero el centro de costos de los puntos de venta que la contienen y luego regrese a borrarlo" } %></div></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/centers/new.js.erb
$('<%= j render "form", title: "Registrar Nuevo Centro de Costos" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/centers/update.html.erb
<% if @c.errors.empty? %>
  // add the row to the table, show alert and hide modal
  $('table tbody tr#<%= @c.id %>').replaceWith(' <%= j render "row", center: @c %>');
  $('.alert-success').html("El centro de costos ha sido modificado").show();
  $('#center-modal').modal('hide');
<% else %>
  // show first error
  alert('<%= @c.errors.full_messages[0] %>');
<% end %>

app/views/centers/update.js.erb
<% if @c.errors.empty? %>
  // add the row to the table, show alert and hide modal
  $('table tbody tr#<%= @c.id %>').replaceWith(' <%= j render "row", center: @c %>');
  $('.alert-success').html("El centro de costos ha sido modificado").show();
  $('#center-modal').modal('hide');
<% else %>
  // show first error
  alert('<%= @c.errors.full_messages[0] %>');
<% end %>